name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            output
            node_modules
            bower_components
          key: build-artifacts-v1-${{ hashFiles('package.json', 'bower.json') }}

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm i

      - run: npm run build
